### ISSUE TITLE
雖然舔錶網快成為絕響但還是很好奇

### ISSUE THREAD

**Issue by awaww333** [breathing-is-fun/liver-collection#53]
首先先感謝作者更新!
但還是很好奇
為何一鍵舔表無法作用在eriri和gbf.life上 (點icon卻能導去召喚頁)
這兩個網站的copy與teemo和Walfie有啥區別

**Comment by orzyyyy** [comment]
1. [这里](https://github.com/peko-bot/liver-collection/blob/master/manifest.json#L13)限定了网站的使用范围。
2. [这里](https://github.com/peko-bot/liver-collection/blob/master/contentScript.ts#L44)其实也限定了能跳转的网站地址。

无它，我就熟悉 teemo 这个网站，看着够用，也就没去关注别的舔婊网了。
1.x 的版本，是要从舔婊网的 dom 中获取 room id 的，所以会有“换了个舔婊网怎么就不能用”的问题。
2.x 则是把监听网页内部所有点击事件，本质上还是监听了剪切板，这样理论上就可以兼容所有“点击复制到剪切板”的舔婊网。不能用则是因为上面的第一点里的代码，限制了扩展的可用地址。

**Comment by awaww333** [comment]
就是有將網站加入manifest依舊無法導向才覺得奇怪
沒事，既然修復了teemo就用到最後一刻吧

**Comment by orzyyyy** [comment]
已经内置了，这代脚本还是落幕了。不过可以期待下很久很久以后的 3.0，主要功能是后台请求列表 api，有房直接进。
